import { expect, test } from "@playwright/test";

test("default Flow Canvas supports Inspector inputs, refs, insertion, deletion and save", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("navigation", { name: "Modules" }).getByRole("button", { name: "Flow" }).click();
  await page.getByRole("button", { name: "New Flow", exact: true }).click();
  await expect(page.getByLabel("Flow Canvas", { exact: true })).toBeVisible();
  const inspector = page.getByRole("complementary", { name: "Inspector" });
  await inspector.getByRole("button", { name: "Add input", exact: true }).click();
  await inspector.getByLabel("Input name", { exact: true }).fill("endpoint");
  await inspector.getByRole("combobox", { name: "Type", exact: true }).selectOption("string");
  await page.locator('.react-flow__node').filter({ hasText: "API Request" }).click();
  await expect(inspector.getByRole("textbox", { name: "Step name", exact: true })).toBeVisible();
  await inspector.getByLabel("Add parameter").selectOption("url");
  await inspector.getByLabel("URL · Type").selectOption("variable");
  await inspector.getByLabel("URL · Variable").selectOption({ label: "Start · endpoint" });
  await expect(inspector.getByText("endpoint", { exact: true })).toBeVisible();
  await page.getByLabel("Insert on connection").selectOption({ label: "Start → API Request" });
  await page.getByLabel("Add step", { exact: true }).selectOption("condition");
  await expect(inspector.getByRole("combobox", { name: "If true", exact: true })).toHaveValue(await inspector.getByRole("combobox", { name: "If false", exact: true }).inputValue());
  await inspector.getByRole("textbox", { name: "Step name", exact: true }).fill("Choose path");
  await page.getByRole("button", { name: "Fit view" }).click();
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByText("r1", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/flow-canvas-inspector.png" });
  await inspector.getByRole("button", { name: "Remove", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("Affected paths");
  await dialog.getByRole("button", { name: "Remove", exact: true }).click();
  await expect(page.locator(".react-flow__node")).toHaveCount(3);
  await expect(inspector.getByLabel("Input name")).toHaveValue("endpoint");
  await page.getByLabel("Add step", { exact: true }).selectOption("condition");
  await inspector.getByLabel("Condition · Value · Variable").selectOption({ label: "Step outputs · API Request · body" });
  await page.getByRole("button", { name: "Fit view" }).click();
  await page.locator(".react-flow__node").filter({ hasText: "API Request" }).click();
  await inspector.getByRole("button", { name: "Remove", exact: true }).first().click();
  await expect(dialog).toContainText("Update these referencing steps before deleting");
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByText("r2", { exact: true })).toBeVisible();
  const node = page.locator(".react-flow__node").filter({ hasText: "API Request" });
  const box = await node.boundingBox();
  if (!box) throw new Error("Node has no layout");
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2 + 40, { steps: 5 });
  await page.mouse.up();
  await expect(page.getByText("r2", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
