[package]
name = "unfour-flow-engine"
version.workspace = true
edition = "2021"
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
serde_json = "1"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["macros", "rt", "time", "sync"] }
tokio-util = "0.7"
unfour-core = { path = "../unfour-core" }
unfour-local-storage = { path = "../local-storage" }
