use std::collections::HashMap;

use sqlx::SqliteConnection;
use unfour_core::domain::{DomainEntityType, DomainSnapshot};
use unfour_ssh_engine::SshService;

use super::SyncRepository;
use crate::canonical::{canonical_snapshot_intent, parse_snapshot_item};
use crate::conflict_scope;
use crate::{
    Clock, IdGenerator, RemoteChange, SnapshotItem, SyncBinding, SyncEntityType, SyncError,
    SyncOperation, PAYLOAD_SCHEMA_VERSION,
};

pub(crate) struct ConnectionV4BootstrapPlan {
    pub apply_items: Vec<SnapshotItem>,
    pub initial_total_increment: i64,
    pub initial_confirmed_increment: i64,
}

fn snapshot_remote_change(item: &SnapshotItem) -> RemoteChange {
    RemoteChange {
        cursor: 0,
        operation_id: format!(
            "connection-v4-bootstrap:{}:{}",
            item.entity_id, item.server_version
        ),
        entity_type: SyncEntityType::Connection,
        entity_id: item.entity_id.clone(),
        parent_entity_id: None,
        operation: SyncOperation::Upsert,
        server_version: item.server_version,
        payload_schema_version: item.payload_schema_version,
        payload: Some(item.payload.clone()),
        deleted_at: None,
    }
}

fn connection_payloads_match(left: &serde_json::Value, right: &serde_json::Value) -> bool {
    let mut left = left.clone();
    let mut right = right.clone();
    let (Some(left), Some(right)) = (left.as_object_mut(), right.as_object_mut()) else {
        return false;
    };
    // Timestamps are local metadata for a Connection aggregate. They can be
    // regenerated by a restore or by another device without changing the
    // cloud-visible Connection fields that should drive reconciliation.
    left.remove("createdAt");
    left.remove("updatedAt");
    right.remove("createdAt");
    right.remove("updatedAt");
    left == right
}

impl SyncRepository {
    /// Claims a pending Connection v4 upgrade and prepares its local outbox,
    /// remote state, and conflict rows on the caller's transaction. The
    /// caller applies `apply_items` through Core before completing the same
    /// transaction, so a failed Core apply leaves the bootstrap pending.
    pub(crate) async fn prepare_connection_v4_on(
        connection: &mut SqliteConnection,
        binding: &SyncBinding,
        snapshots: Vec<DomainSnapshot>,
        remote_items: &[SnapshotItem],
        ids: &dyn IdGenerator,
        clock: &dyn Clock,
    ) -> Result<Option<ConnectionV4BootstrapPlan>, SyncError> {
        if binding.connection_v4_bootstrap_state == "completed" {
            return Ok(None);
        }

        let now = clock.now();
        let now_text = now.to_rfc3339();
        let claimed = sqlx::query(
            r#"UPDATE cloud_sync_workspace_bindings
               SET connection_v4_bootstrap_state = 'pending', updated_at = ?1
               WHERE account_id = ?2 AND local_workspace_id = ?3
                 AND cloud_workspace_id = ?4 AND generation = ?5
                 AND connection_v4_bootstrap_state = 'pending'
                 AND sync_enabled = 1 AND state <> 'paused'
                 AND EXISTS (
                   SELECT 1 FROM cloud_sync_account_settings
                   WHERE account_id = ?2 AND sync_enabled = 1
                 )"#,
        )
        .bind(&now_text)
        .bind(&binding.account_id)
        .bind(&binding.local_workspace_id)
        .bind(&binding.cloud_workspace_id)
        .bind(binding.generation)
        .execute(&mut *connection)
        .await?
        .rows_affected();
        if claimed == 0 {
            let completed: bool = sqlx::query_scalar(
                r#"SELECT EXISTS(SELECT 1 FROM cloud_sync_workspace_bindings
                   WHERE account_id = ?1 AND local_workspace_id = ?2
                     AND cloud_workspace_id = ?3 AND generation = ?4
                     AND connection_v4_bootstrap_state = 'completed'
                     AND sync_enabled = 1 AND state <> 'paused'
                     AND EXISTS (
                       SELECT 1 FROM cloud_sync_account_settings
                       WHERE account_id = ?1 AND sync_enabled = 1
                     ))"#,
            )
            .bind(&binding.account_id)
            .bind(&binding.local_workspace_id)
            .bind(&binding.cloud_workspace_id)
            .bind(binding.generation)
            .fetch_one(&mut *connection)
            .await?;
            return completed.then_some(None).ok_or(SyncError::AccountChanged);
        }

        let mut local_by_id = HashMap::with_capacity(snapshots.len());
        for snapshot in snapshots {
            let snapshot = canonical_snapshot_intent(snapshot)?;
            if snapshot.entity.workspace_id != binding.local_workspace_id
                || snapshot.entity.entity_type != DomainEntityType::Connection
                || snapshot.entity.parent_entity_id.is_some()
            {
                return Err(SyncError::InvalidData);
            }
            if snapshot.intent.operation != SyncOperation::Delete {
                if local_by_id
                    .insert(snapshot.entity.entity_id.clone(), snapshot)
                    .is_some()
                {
                    return Err(SyncError::InvalidData);
                }
            }
        }

        let mut remote_by_id = HashMap::with_capacity(remote_items.len());
        for item in remote_items {
            if item.entity_type != SyncEntityType::Connection
                || item.parent_entity_id.is_some()
                || item.server_version < 1
                || item.payload_schema_version != PAYLOAD_SCHEMA_VERSION
            {
                return Err(SyncError::InvalidData);
            }
            // Validate the canonical payload before any Core apply. This also
            // verifies that the repeated Connection identity targets this
            // local workspace and that no device-local material is present.
            parse_snapshot_item(&binding.local_workspace_id, item)?;
            if remote_by_id
                .insert(item.entity_id.clone(), item.clone())
                .is_some()
            {
                return Err(SyncError::InvalidData);
            }
        }

        let mut apply_items = Vec::new();
        let mut initial_confirmed_increment = 0_i64;

        for (entity_id, snapshot) in &local_by_id {
            let Some(remote) = remote_by_id.get(entity_id) else {
                Self::enqueue_intent_on(
                    connection,
                    &binding.account_id,
                    &binding.local_workspace_id,
                    &binding.cloud_workspace_id,
                    entity_id,
                    snapshot.revision,
                    snapshot.intent.clone(),
                    ids.next_id(),
                    now,
                )
                .await?;
                continue;
            };

            let local_payload: serde_json::Value = snapshot
                .intent
                .payload_json
                .as_deref()
                .ok_or(SyncError::InvalidData)
                .and_then(|value| {
                    serde_json::from_str(value).map_err(|_| SyncError::InvalidData)
                })?;
            if connection_payloads_match(&local_payload, &remote.payload) {
                Self::remove_equivalent_pending_connection_outbox_on(
                    connection,
                    binding,
                    entity_id,
                    &remote.payload,
                )
                .await?;
                Self::record_remote_state_on(
                    connection,
                    binding,
                    &snapshot_remote_change(remote),
                    "synced",
                    &now_text,
                )
                .await?;
                if binding.state == "uploading" {
                    initial_confirmed_increment += 1;
                }
                continue;
            }

            let local_intent = conflict_scope::has_local_intent_on(
                connection,
                binding,
                SyncEntityType::Connection,
                entity_id,
                SyncOperation::Upsert,
            )
            .await?;
            let previous_remote = Self::connection_state_on(connection, binding, entity_id).await?;
            let safe_remote_update = !local_intent
                && previous_remote.is_some_and(|(version, status)| {
                    status == "synced" && version > 0 && version < remote.server_version
                });
            if safe_remote_update {
                apply_items.push(remote.clone());
                Self::record_remote_state_on(
                    connection,
                    binding,
                    &snapshot_remote_change(remote),
                    "synced",
                    &now_text,
                )
                .await?;
            } else {
                // With no prior server state, a real shared-field divergence
                // does not prove that either side is newer. Keep the upgrade
                // conservative and use the existing conflict flow; metadata
                // timestamp-only differences were handled above.
                Self::record_connection_bootstrap_conflict_on(
                    connection, binding, remote, &now_text,
                )
                .await?;
            }
        }

        for (entity_id, remote) in &remote_by_id {
            if local_by_id.contains_key(entity_id) {
                continue;
            }
            apply_items.push(remote.clone());
            Self::record_remote_state_on(
                connection,
                binding,
                &snapshot_remote_change(remote),
                "synced",
                &now_text,
            )
            .await?;
        }

        // HashMap iteration is intentionally not part of the reconciliation
        // contract, but deterministic Core apply order makes retries and
        // diagnostics stable.
        apply_items.sort_unstable_by(|left, right| left.entity_id.cmp(&right.entity_id));

        Ok(Some(ConnectionV4BootstrapPlan {
            apply_items,
            initial_total_increment: if binding.state == "uploading" {
                local_by_id.len() as i64
            } else {
                0
            },
            initial_confirmed_increment,
        }))
    }

    async fn connection_state_on(
        connection: &mut SqliteConnection,
        binding: &SyncBinding,
        entity_id: &str,
    ) -> Result<Option<(i64, String)>, SyncError> {
        sqlx::query_as(
            r#"SELECT server_version, sync_status
               FROM cloud_sync_entity_state
               WHERE account_id = ?1 AND cloud_workspace_id = ?2
                 AND entity_type = 'connection' AND entity_id = ?3"#,
        )
        .bind(&binding.account_id)
        .bind(&binding.cloud_workspace_id)
        .bind(entity_id)
        .fetch_optional(&mut *connection)
        .await
        .map_err(Into::into)
    }

    async fn remove_equivalent_pending_connection_outbox_on(
        connection: &mut SqliteConnection,
        binding: &SyncBinding,
        entity_id: &str,
        remote_payload: &serde_json::Value,
    ) -> Result<(), SyncError> {
        let rows: Vec<(String, String, Option<String>)> = sqlx::query_as(
            r#"SELECT operation_id, status, canonical_payload_json
               FROM cloud_sync_outbox
               WHERE account_id = ?1 AND cloud_workspace_id = ?2
                 AND entity_type = 'connection' AND entity_id = ?3"#,
        )
        .bind(&binding.account_id)
        .bind(&binding.cloud_workspace_id)
        .bind(entity_id)
        .fetch_all(&mut *connection)
        .await?;
        for (operation_id, status, payload_json) in rows {
            if !matches!(status.as_str(), "pending" | "uncertain") {
                continue;
            }
            let Some(payload_json) = payload_json else {
                continue;
            };
            let payload: serde_json::Value =
                serde_json::from_str(&payload_json).map_err(|_| SyncError::InvalidData)?;
            if !connection_payloads_match(&payload, remote_payload) {
                continue;
            }
            sqlx::query(
                "DELETE FROM cloud_sync_outbox WHERE account_id = ?1 AND cloud_workspace_id = ?2 AND operation_id = ?3",
            )
            .bind(&binding.account_id)
            .bind(&binding.cloud_workspace_id)
            .bind(operation_id)
            .execute(&mut *connection)
            .await?;
        }
        Ok(())
    }

    async fn record_connection_bootstrap_conflict_on(
        connection: &mut SqliteConnection,
        binding: &SyncBinding,
        item: &SnapshotItem,
        now: &str,
    ) -> Result<(), SyncError> {
        let change = snapshot_remote_change(item);
        Self::record_remote_state_on(connection, binding, &change, "conflict", now).await?;
        sqlx::query(
            r#"UPDATE cloud_sync_workspace_bindings
               SET state = 'conflict', last_error = 'remote_local_conflict', updated_at = ?1
               WHERE account_id = ?2 AND local_workspace_id = ?3"#,
        )
        .bind(now)
        .bind(&binding.account_id)
        .bind(&binding.local_workspace_id)
        .execute(&mut *connection)
        .await?;
        Self::record_diagnostic_on(
            connection,
            &binding.account_id,
            Some(&binding.cloud_workspace_id),
            "conflict",
            "remote_local_conflict",
            Some(SyncEntityType::Connection.as_str()),
            Some(&item.entity_id),
            now,
        )
        .await
    }

    pub(crate) async fn complete_connection_v4_on(
        connection: &mut SqliteConnection,
        binding: &SyncBinding,
        plan: &ConnectionV4BootstrapPlan,
        clock: &dyn Clock,
    ) -> Result<(), SyncError> {
        let now = clock.now().to_rfc3339();
        let completed = sqlx::query(
            r#"UPDATE cloud_sync_workspace_bindings
               SET connection_v4_bootstrap_state = 'completed',
                   initial_total = initial_total + ?2,
                   initial_confirmed = MIN(
                     initial_total + ?2,
                     initial_confirmed + ?3
                   ),
                   updated_at = ?1
               WHERE account_id = ?4 AND local_workspace_id = ?5
                 AND cloud_workspace_id = ?6 AND generation = ?7
                 AND connection_v4_bootstrap_state = 'pending'"#,
        )
        .bind(&now)
        .bind(plan.initial_total_increment)
        .bind(plan.initial_confirmed_increment)
        .bind(&binding.account_id)
        .bind(&binding.local_workspace_id)
        .bind(&binding.cloud_workspace_id)
        .bind(binding.generation)
        .execute(&mut *connection)
        .await?
        .rows_affected();
        if completed != 1 {
            return Err(SyncError::AccountChanged);
        }
        Ok(())
    }

    /// Backfills SSH Task protocol-v3 intents for a binding created by an
    /// older client. The no-op update acquires SQLite's write lock before the
    /// state check, so concurrent processes cannot both perform the backfill.
    /// Intent writes and the completed marker commit atomically.
    pub async fn bootstrap_ssh_task_v3(
        &self,
        binding: &SyncBinding,
        ssh: &SshService,
        ids: &dyn IdGenerator,
        clock: &dyn Clock,
    ) -> Result<bool, SyncError> {
        if binding.ssh_task_v3_bootstrap_state == "completed" {
            return Ok(false);
        }

        let now = clock.now();
        let now_text = now.to_rfc3339();
        let mut tx = self.pool.begin().await?;
        let claimed = sqlx::query(
            r#"UPDATE cloud_sync_workspace_bindings
               SET ssh_task_v3_bootstrap_state = 'pending'
               WHERE account_id = ?1 AND local_workspace_id = ?2
                 AND cloud_workspace_id = ?3 AND generation = ?4
                 AND ssh_task_v3_bootstrap_state = 'pending'
                 AND sync_enabled = 1 AND state <> 'paused'
                 AND EXISTS (
                   SELECT 1 FROM cloud_sync_account_settings
                   WHERE account_id = ?1 AND sync_enabled = 1
                 )"#,
        )
        .bind(&binding.account_id)
        .bind(&binding.local_workspace_id)
        .bind(&binding.cloud_workspace_id)
        .bind(binding.generation)
        .execute(&mut *tx)
        .await?
        .rows_affected();
        if claimed == 0 {
            let completed: bool = sqlx::query_scalar(
                r#"SELECT EXISTS(SELECT 1 FROM cloud_sync_workspace_bindings
                   WHERE account_id = ?1 AND local_workspace_id = ?2
                     AND cloud_workspace_id = ?3 AND generation = ?4
                     AND ssh_task_v3_bootstrap_state = 'completed'
                     AND sync_enabled = 1 AND state <> 'paused'
                     AND EXISTS (
                       SELECT 1 FROM cloud_sync_account_settings
                       WHERE account_id = ?1 AND sync_enabled = 1
                     ))"#,
            )
            .bind(&binding.account_id)
            .bind(&binding.local_workspace_id)
            .bind(&binding.cloud_workspace_id)
            .bind(binding.generation)
            .fetch_one(&mut *tx)
            .await?;
            tx.commit().await?;
            return completed.then_some(false).ok_or(SyncError::AccountChanged);
        }

        let keys = ssh
            .list_task_domain_entities_on(&mut tx, &binding.local_workspace_id)
            .await
            .map_err(|_| SyncError::Core)?;
        for key in &keys {
            if key.workspace_id != binding.local_workspace_id
                || !matches!(
                    key.entity_type,
                    DomainEntityType::SshTask | DomainEntityType::SshTaskStep
                )
            {
                return Err(SyncError::InvalidData);
            }
            let snapshot = ssh
                .read_task_domain_snapshot_on(&mut tx, key)
                .await
                .map_err(|_| SyncError::Core)?;
            let snapshot = canonical_snapshot_intent(snapshot)?;
            if snapshot.entity.workspace_id != binding.local_workspace_id {
                return Err(SyncError::InvalidData);
            }
            if snapshot.intent.operation == SyncOperation::Delete {
                continue;
            }
            Self::enqueue_intent_on(
                &mut tx,
                &binding.account_id,
                &binding.local_workspace_id,
                &binding.cloud_workspace_id,
                &snapshot.entity.entity_id,
                snapshot.revision,
                snapshot.intent,
                ids.next_id(),
                now,
            )
            .await?;
        }

        let completed = sqlx::query(
            r#"UPDATE cloud_sync_workspace_bindings
               SET ssh_task_v3_bootstrap_state = 'completed', updated_at = ?1
               WHERE account_id = ?2 AND local_workspace_id = ?3
                 AND cloud_workspace_id = ?4 AND generation = ?5
                 AND ssh_task_v3_bootstrap_state = 'pending'"#,
        )
        .bind(&now_text)
        .bind(&binding.account_id)
        .bind(&binding.local_workspace_id)
        .bind(&binding.cloud_workspace_id)
        .bind(binding.generation)
        .execute(&mut *tx)
        .await?
        .rows_affected();
        if completed != 1 {
            return Err(SyncError::AccountChanged);
        }
        tx.commit().await?;
        Ok(true)
    }
}
